# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!


target 'StarWarsApp' do

  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'R.swift'
  pod 'SwiftLint'

  target 'StarWarsAppTests' do

     pod 'RxBlocking', '~> 4.0'
     pod 'RxTest',     '~> 4.0'

  end

end